# Generated by Django 6.0.3 on 2026-03-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='Update Soon', max_length=70),
            preserve_default=False,
        ),
    ]
